dataset_path: lmms-lab/MMMU
task: "mmmu_val_boxed"
test_split: validation
output_type: generate_until
doc_to_visual: !function utils.mmmu_doc_to_visual
doc_to_text: !function utils.mmmu_doc_to_text
doc_to_target: "answer"
doc_to_messages: !function utils.mmmu_doc_to_messages
process_results: !function utils_boxed.mmmu_process_results
generation_kwargs:
  max_new_tokens: 8192
  until: []

metric_list:
  - metric: mmmu_acc
    aggregation: !function utils.mmmu_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    prompt_type: "format"
    multiple_choice_prompt: "Answer with the option's letter from the given choices directly. Put your final answer in \\boxed{}."
    open_ended_prompt: "Answer the question using a single word or phrase. Put your final answer in \\boxed{}."
  qwen3_vl:
    format: "qwen3_vl"
    pre_prompt: "Question: "
    post_prompt: "Answer with the option letter only. Put your final answer in \\boxed{}."
    open_ended_prompt: "Please select the correct answer from the options above. Put your final answer in \\boxed{}."
include: _default_template_yaml
