include: _default_template_yaml_boxed
task: mvbench_action_prediction_boxed
dataset_name: action_prediction
test_split: train
lmms_eval_specific_kwargs:
  default:
    sub_task: action_prediction
    post_prompt: "Only give the best option letter. Put your final answer in \\boxed{}.\n"

