from transformers import PretrainedConfig


class SmolAllocatorConfig(PretrainedConfig):
    model_type = "smol_allocator"

    def __init__(
        self,
        smol_model_name: str = "HuggingFaceTB/SmolVLM2-256M-Video-Instruct",
        fps: float = 2.0,
        vocab_size: int = 49280,
        patch_size: int = 16,
        torch_dtype: str | None = None,
        _attn_implementation: str | None = None,
        spatial_merge_size: int = 2,
        hidden_size: int = 768,
        vision_hidden_size: int = 768,
        llm_hidden_size: int = 768,
        out_hidden_size: int = 768,
        output_dim: int = 768,
        self_depth: int = 2,
        cross_depth: int = 1,
        dim_head: int = 64,
        num_heads: int = 8,
        max_frames: int = 8,
        min_scale: float = 0.2,
        max_scale: float = 2.0,
        use_discrete_action: bool = False,
        use_text: bool = True,
        use_differentiable_importance: bool = False,
        use_text_encoder: bool = False,
        text_encoder_depth: int = 0,
        text_encoder_heads: int | None = None,
        text_encoder_dropout: float = 0.0,
        text_encoder_ff_mult: int = 4,
        mlp_mode: str = "mlp",
        vlp_mode: str = "mlp",
        regression_head_mode: str = "mlp",
        dropout: float = 0.0,
        ff_mult: int = 4,
        scale_bins: list | None = None,
        beta_add_one: bool = True,
        beta_init_mode: str = "uniform",
        frame_temporal_depth: int = 2,
        use_text_conditioned_spatial: bool = False,
        enable_rope_cache: bool = True,
        use_dirichlet_budget: bool = False,
        dirichlet_budget: float = 1.0,
        dirichlet_eps: float = 1e-6,
        use_frame_info: bool = False,
        use_learned_pooling: bool = False,
        frame_info_ema_alpha: float = 0.9,
        init_head: bool = True,
        init_scale_mean: float = 1.0,
        init_concentration: float = 4.0,
        init_weight_std: float = 1e-2,
        dirichlet_logit_noise_std: float = 0.0,
        dirichlet_init_weight_std: float | None = None,
        force_uniform_ab: bool = False,
        layer_weighted_num_layers: int = 0,
        layer_fusion_mode: str = "none",
        layer_fusion_indices: list | None = None,
        gate_mode: str = "gumbel_softmax",
        gate_k_ratio: float = 0.25,
        gate_temperature: float = 1.0,
        gate_query_scale: float = 1.0,
        continuous_dist: str = "beta",
        continuous_eval_quantile: float = 0.5,
        beta_param_scale: float = 1.0,
        logistic_normal_init_sigma: float = 0.7,
        categorical_temperature: float = 1.0,
        pool_gate_mode: str = "no_ln",
        info_fuse_mode: str = "pooled_ln",
        contrastive_weight: float = 0.1,
        contrastive_temperature: float = 0.1,
        contrastive_margin: float = 0.0,
        sim_scale_weight: float = 0.0,
        sim_tau: float = 0.5,
        sim_temp: float = 0.1,
        sim_gamma: float = 0.05,
        temporal_mixer_depth: int = 1,
        temporal_use_pos: bool = True,
        dual_path_depth: int = 1,
        use_cross_attn_gate: bool = False,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.smol_model_name = smol_model_name
        self.fps = fps
        self.vocab_size = vocab_size
        self.patch_size = patch_size
        self.torch_dtype = torch_dtype
        self._attn_implementation = _attn_implementation
        self.spatial_merge_size = spatial_merge_size
        self.hidden_size = hidden_size
        self.vision_hidden_size = vision_hidden_size
        self.llm_hidden_size = llm_hidden_size
        self.out_hidden_size = out_hidden_size
        self.output_dim = output_dim
        self.self_depth = self_depth
        self.cross_depth = cross_depth
        self.dim_head = dim_head
        self.num_heads = num_heads
        self.max_frames = max_frames
        self.min_scale = min_scale
        self.max_scale = max_scale
        self.use_discrete_action = use_discrete_action
        self.use_text = use_text
        self.use_differentiable_importance = use_differentiable_importance
        self.use_text_encoder = use_text_encoder
        self.text_encoder_depth = text_encoder_depth
        self.text_encoder_heads = text_encoder_heads
        self.text_encoder_dropout = text_encoder_dropout
        self.text_encoder_ff_mult = text_encoder_ff_mult
        self.use_cross_attn_gate = use_cross_attn_gate
        self.mlp_mode = mlp_mode
        self.vlp_mode = vlp_mode
        self.regression_head_mode = regression_head_mode
        self.dropout = dropout
        self.ff_mult = ff_mult
        self.scale_bins = scale_bins
        self.beta_add_one = beta_add_one
        self.beta_init_mode = beta_init_mode
        self.frame_temporal_depth = frame_temporal_depth
        self.use_text_conditioned_spatial = use_text_conditioned_spatial
        self.enable_rope_cache = enable_rope_cache
        self.use_dirichlet_budget = use_dirichlet_budget
        self.dirichlet_budget = dirichlet_budget
        self.dirichlet_eps = dirichlet_eps
        self.use_frame_info = use_frame_info
        self.use_learned_pooling = use_learned_pooling
        self.frame_info_ema_alpha = frame_info_ema_alpha
        self.init_head = init_head
        self.init_scale_mean = init_scale_mean
        self.init_concentration = init_concentration
        self.init_weight_std = init_weight_std
        self.dirichlet_logit_noise_std = dirichlet_logit_noise_std
        self.dirichlet_init_weight_std = dirichlet_init_weight_std
        self.force_uniform_ab = force_uniform_ab
        self.layer_weighted_num_layers = layer_weighted_num_layers
        self.layer_fusion_mode = layer_fusion_mode
        self.layer_fusion_indices = layer_fusion_indices
        self.gate_mode = gate_mode
        self.gate_k_ratio = gate_k_ratio
        self.gate_temperature = gate_temperature
        self.gate_query_scale = gate_query_scale
        self.continuous_dist = continuous_dist
        self.continuous_eval_quantile = continuous_eval_quantile
        self.beta_param_scale = beta_param_scale
        self.logistic_normal_init_sigma = logistic_normal_init_sigma
        self.categorical_temperature = categorical_temperature
        self.pool_gate_mode = pool_gate_mode
        self.info_fuse_mode = info_fuse_mode
        self.contrastive_weight = contrastive_weight
        self.contrastive_temperature = contrastive_temperature
        self.contrastive_margin = contrastive_margin
        self.sim_scale_weight = sim_scale_weight
        self.sim_tau = sim_tau
        self.sim_temp = sim_temp
        self.sim_gamma = sim_gamma
        self.temporal_mixer_depth = temporal_mixer_depth
        self.temporal_use_pos = temporal_use_pos
        self.dual_path_depth = dual_path_depth

    def get(self, key, default=None):
        return getattr(self, key, default)


__all__ = ["SmolAllocatorConfig"]
